-- Step 1.1: Create Global Settings Table
CREATE TABLE public.settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT UNIQUE NOT NULL,
    value TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert the default booking duration setting
INSERT INTO public.settings (key, value) VALUES ('default_booking_duration_minutes', '60');

-- Enable RLS
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;

-- RLS Policy: Read access for all authenticated users
CREATE POLICY "All authenticated users can view settings" 
ON public.settings 
FOR SELECT 
USING (auth.role() = 'authenticated');

-- RLS Policy: Only service role can write
CREATE POLICY "Only service role can manage settings" 
ON public.settings 
FOR ALL 
USING (auth.role() = 'service_role');