import { lazy } from 'react';

// Lazy load all major page components
const BookingPage = lazy(() => import("@/pages/BookingPage"));
const UsersPage = lazy(() => import("@/pages/UsersPage"));
const TeachersPage = lazy(() => import("@/pages/TeachersPage"));
const HallsPage = lazy(() => import("@/pages/HallsPage"));
const StagesPage = lazy(() => import("@/pages/StagesPage"));
const SubjectsPage = lazy(() => import("@/pages/SubjectsPage"));
const BookingsPage = lazy(() => import("@/pages/BookingsPage"));
const StudentsPage = lazy(() => import("@/pages/StudentsPage"));
const StudentRegistrationsPage = lazy(() => import("@/pages/StudentRegistrationsPage"));
const ClassManagementPage = lazy(() => import("@/pages/ClassManagementPage"));
const AttendanceManagementPage = lazy(() => import("@/pages/AttendanceManagementPage"));
const MonthlyReportsPage = lazy(() => import("@/pages/MonthlyReportsPage"));
const MonthlyFeeManager = lazy(() => import("@/pages/MonthlyFeeManagerPage"));
const StudentRelocationManager = lazy(() => import("@/pages/StudentRelocationPage"));
const AdminPrivilegesPage = lazy(() => import("@/pages/AdminPrivilegesPage"));
const DailyExpensesPage = lazy(() => import("@/pages/DailyExpensesPage"));
const ExpensesPage = lazy(() => import("@/pages/ExpensesPage"));
const DailySettlementPage = lazy(() => import("@/pages/DailySettlementPage"));
const ActualLiquidityPage = lazy(() => import("@/pages/ActualLiquidityPage"));
const TeacherDashboard = lazy(() => import("@/pages/TeacherDashboard"));
const StudentLoginPage = lazy(() => import("@/pages/StudentLoginPage"));
const StudentDashboard = lazy(() => import("@/pages/StudentDashboard"));
const NotFound = lazy(() => import("@/pages/NotFound"));

export const LazyBookingPage = BookingPage;
export const LazyUsersPage = UsersPage;
export const LazyTeachersPage = TeachersPage;
export const LazyHallsPage = HallsPage;
export const LazyStagesPage = StagesPage;
export const LazySubjectsPage = SubjectsPage;
export const LazyBookingsPage = BookingsPage;
export const LazyStudentsPage = StudentsPage;
export const LazyStudentRegistrationsPage = StudentRegistrationsPage;
export const LazyClassManagementPage = ClassManagementPage;
export const LazyAttendanceManagementPage = AttendanceManagementPage;
export const LazyMonthlyReportsPage = MonthlyReportsPage;
export const LazyMonthlyFeeManager = MonthlyFeeManager;
export const LazyStudentRelocationManager = StudentRelocationManager;
export const LazyAdminPrivilegesPage = AdminPrivilegesPage;
export const LazyDailyExpensesPage = DailyExpensesPage;
export const LazyExpensesPage = ExpensesPage;
export const LazyDailySettlementPage = DailySettlementPage;
export const LazyActualLiquidityPage = ActualLiquidityPage;
export const LazyTeacherDashboard = TeacherDashboard;
export const LazyStudentLoginPage = StudentLoginPage;
export const LazyStudentDashboard = StudentDashboard;
export const LazyNotFound = NotFound;