-- Fix auth.users table NULL values that are causing login errors
UPDATE auth.users 
SET 
    email_change = '',
    email_change_token_new = '',
    email_change_token_current = '',
    email_change_confirm_status = 0,
    phone_change = '',
    phone_change_token = '',
    phone_change_confirm_status = 0,
    confirmation_token = COALESCE(confirmation_token, ''),
    recovery_token = COALESCE(recovery_token, ''),
    email_change_sent_at = NULL,
    phone_change_sent_at = NULL,
    confirmation_sent_at = NULL,
    recovery_sent_at = NULL,
    email_confirmed_at = COALESCE(email_confirmed_at, now()),
    phone_confirmed_at = NULL,
    last_sign_in_at = NULL,
    raw_app_meta_data = COALESCE(raw_app_meta_data, '{"provider": "email", "providers": ["email"]}'::jsonb),
    raw_user_meta_data = COALESCE(raw_user_meta_data, '{"full_name": "System Administrator"}'::jsonb),
    is_sso_user = false,
    deleted_at = NULL,
    is_anonymous = false
WHERE email = 'admin@admin.com' OR id = '00000000-0000-0000-0000-000000000001';

-- Ensure admin user exists with all required fields
INSERT INTO auth.users (
    id,
    instance_id,
    email,
    encrypted_password,
    email_confirmed_at,
    created_at,
    updated_at,
    role,
    aud,
    confirmation_token,
    email_change_token_new,
    email_change_token_current,
    raw_app_meta_data,
    raw_user_meta_data,
    email_change,
    phone_change,
    email_change_confirm_status,
    phone_change_confirm_status,
    phone_change_token,
    recovery_token,
    is_sso_user,
    deleted_at,
    is_anonymous
) VALUES (
    '00000000-0000-0000-0000-000000000001',
    '00000000-0000-0000-0000-000000000000',
    'admin@admin.com',
    crypt('Voda@123', gen_salt('bf')),
    now(),
    now(),
    now(),
    'authenticated',
    'authenticated',
    '',
    '',
    '',
    '{"provider": "email", "providers": ["email"]}',
    '{"full_name": "System Administrator"}',
    '',
    '',
    0,
    0,
    '',
    '',
    false,
    NULL,
    false
) ON CONFLICT (id) DO UPDATE SET
    encrypted_password = crypt('Voda@123', gen_salt('bf')),
    email = 'admin@admin.com',
    email_change = '',
    email_change_token_new = '',
    email_change_token_current = '',
    phone_change = '',
    phone_change_token = '',
    recovery_token = '',
    confirmation_token = '',
    email_change_confirm_status = 0,
    phone_change_confirm_status = 0,
    is_sso_user = false,
    is_anonymous = false,
    updated_at = now();