// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lhklufuwbtjexsehlvtj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxoa2x1ZnV3YnRqZXhzZWhsdnRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1MTcyNTMsImV4cCI6MjA2NTA5MzI1M30.lRp-zyA9I3wwfBE8rT24oYJyzWS3_1QJRztZg-cnFhg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});